#!/bin/sh

# ██╗    ██╗██╗   ██╗ █████╗ ██╗     
# ██║    ██║██║   ██║██╔══██╗██║     
# ██║ █╗ ██║██║   ██║███████║██║     (code by wual)
# ██║███╗██║██║   ██║██╔══██║██║     
# ╚███╔███╔╝╚██████╔╝██║  ██║███████╗
#  ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚══════╝

# See proyect >> https://github.com/14wual/pycalc
# Follow me >> https://twitter.com/14wual

set -e

cp -r /<paths>/pycal /usr/share/pycalc

chmod +x /usr/bin/pycalc

apt-get install -y python3 python3-pip

pip3 install customtkinter==5.1.3 pyperclip==1.8.2 Pillow==9.5.0 plyer==2.1.0

exit 0
